### ISSUE TITLE
text cropped on raster tile

### ISSUE THREAD

**Issue by germsb** [maptiler/tileserver-gl#344] opened 2019-02-01 15:40 UTC
Docker image klokantech/tileserver-gl

This problem has already been reported here: #184 #35 [224](https://github.com/openmaptiles/openmaptiles/issues/224) and many other

Apparently the problem came from mapbox-gl-native [bug](https://github.com/mapbox/mapbox-gl-native/issues/11838) but it has been fixed since version 4.X
so finally not so sure that the problem comes from there since tileserver-gl uses this latest version!

As workaround, I have tested `"symbol-avoid-edges": true,` in layers layout without positive effects.
### vector tiles ok
![Imgur](https://i.imgur.com/fSu5PRr.jpg)
### raster tiles
![Imgur](https://i.imgur.com/jOR5UXD.jpg)
![Imgur](https://i.imgur.com/mhuBNAr.jpg)

Whatever the style, the problem persists (even those proposed by default)

I use data from openmaptiles.com custom extract who use the schema v3.9. ( ̶r̶a̶s̶t̶e̶r̶ ̶r̶e̶n̶d̶e̶r̶ ̶i̶s̶ ̶o̶k̶ ̶w̶i̶t̶h̶ ̶k̶l̶o̶k̶a̶n̶t̶e̶c̶h̶/̶o̶p̶e̶n̶m̶a̶p̶t̶i̶l̶e̶s̶-̶s̶e̶r̶v̶e̶r̶) and tested also with extractions done with quickstart.sh from openmaptiles/openmaptiles

So what to do?

Otherwise, very good job, I find it just a pity that a bug that is more than 2 years old and which has a rather heavy impact is not resolved or simply better documented

**Comment by BHudsonJSI** [comment] 2019-02-11 19:53
I can confirm I see this same issue in tileserver-gl 2.5.0 and osm-2018-12-03-v3.9.

Check Australia at level 4-7 using either osm-bright or klokantech-basic in raster.  Neither style exhibits this issue in vector.

![image](https://user-images.githubusercontent.com/28735994/52588669-02eb3e00-2e0b-11e9-8d09-80a199b30733.png)

![image](https://user-images.githubusercontent.com/28735994/52588729-244c2a00-2e0b-11e9-82d1-22a08d8874f6.png)

![image](https://user-images.githubusercontent.com/28735994/52588838-6d03e300-2e0b-11e9-8bcf-9de12f54bed7.png)

![image](https://user-images.githubusercontent.com/28735994/52588878-84db6700-2e0b-11e9-986c-567f2de80910.png)

This issue has always been present here and there.  Users are reporting the issue is much more noticeable than in  tileserver-gl 2.3.1 and osm-2018-06-14-v3.8 with the exact same configuration otherwise.

**Comment by petrsloup** [comment] 2019-02-14 16:57
You can try with the `v3` branch -- the issue might be much less frequent in that version.

**Comment by BHudsonJSI** [comment] 2019-02-19 18:31
I tried the v3 branch container, which exhibits the same behaviour.  It looks to be happening in the same places and same frequency in the areas we've checked.

![image](https://user-images.githubusercontent.com/28735994/53038397-a27f8080-344a-11e9-9ffa-d9a79df6cbc1.png)

**Comment by boldtrn** [comment] 2019-03-01 16:36
> You can try with the v3 branch -- the issue might be much less frequent in that version.

I can confirm that v3 looks a lot better. I also applied `"symbol-avoid-edges": true`.

**Comment by BHudsonJSI** [comment] 2019-03-01 21:22
After looking at it some more, v3 is slightly better than v2.5.0 after adding the symbol-avoid-edges option.  v2.4.0 is much better than both v2.5.0 and v3, even without the symbol-avoid-edges.   All versions still have clipping at the lower zooms with lots of POI data.

We're looking at a roll-back to 2.4.0 for the time being.  Once this bug is fixed in a new stable/release version I will look into upgrading again.

**Comment by mo-ian-watkins** [comment] 2019-03-25 19:32
Also rolled back to v2.4 here, just too many labelling issues with v2.5 that we couldn’t live with.

Which is a shame because v2.5 is the minimum needed for OSZoomstack styles/data.

Really need to serve OpenMapTiles data and OS Zoomstack but want to avoid 2 servers.

**Comment by nyurik** [comment] 2019-05-01 15:00
We hit the same issue, had to revert to v2.4 as most of our usecases are raster (sigh).  I saw that v3.0 was referenced a bit earlier, and that v3.0 docker image was published. Does it behave as good as v2.4, or is it still causing issues?

Not sure if related, but it seemed that the majority of issues began happening around the UTC line, whereas in 2.4 the same issues were happening around the antimeridian line - which didn't cause as many problems because it is far less populated and mostly goes over the ocean.

**Comment by tobwen** [comment] 2019-05-06 19:43
@nyurik I've just tested v3 with Positron and it looks nice here.

**Comment by yongzhixu** [comment] 2019-07-13 09:59
how to upgrade from v2.5.0 to V3

**Comment by BHudsonJSI** [comment] 2019-07-13 17:57
> how to upgrade from v2.5.0 to V3

For docker containers, pull it using the v3 version tag.  e.g.
`docker pull klokantech/tileserver-gl:v3`
Be sure to also reference the tag when running the container.

**Comment by petrsloup** [comment] 2019-10-02 10:28
The #379 provides a workaround for this. Other than that, this issue is a mix of vector data (tile buffer) and styling (font size, label positioning, etc.) and there is not much the server can do with that.

**Closed by petrsloup** 2019-10-02 10:28 UTC

**Comment by haxtibal** [comment] 2019-10-09 16:28
Sorry for posing to this closed issue.

I also faced cut text with tileserver-gl 2.5.0 and mapbox-gl-native 4.3.0, and got it fixed by setting `mode: "tile"` in serve_rendered.js as suggested by @ChrisLoer in mapbox/mapbox-gl-native#12763.

Afaikt the suggested map mode setting makes sense:
```
enum class MapMode : EnumType {
    Continuous, // continually updating map
    Static, // a once-off still image of an arbitrary viewport
    Tile // a once-off still image of a single tile
};
```

Any reason why you couldn't pull pathmapper/tileserver-gl@3f2bc21 upstream? Don't know if it fixes the problem for everyone, but where it does, it seems preferable to the `tileMargin` solution that comes with performance drawback.

**Comment by petrsloup** [comment] 2019-10-09 16:30
@haxtibal Yes, this is part of the v3 branch and will be part of the next major release. https://github.com/maptiler/tileserver-gl/commit/d25eb904e934c5426ec064355db6d85ad0988426

**Comment by haxtibal** [comment] 2019-10-09 16:33
@petrsloup Thanks👍
